### ISSUE TITLE
renovasjon og sensorer

### ISSUE THREAD

**Issue by erlendoyen** [Coderaxx/Norske-tjenester#1]
Hei

kjempe messig app!

Et spørsmål: i readme fila står det at det vil bli opprettet sensorer i flertall per type avfall, her ligger alle hentinger under samme enhet, men det er kanskje slik det skal være, en enhet med en sensor/verdi per avfall

![Screenshot_20230418-114432520 (1)](https://user-images.githubusercontent.com/96687238/232739209-357ce21d-acc3-4665-a25f-7bce5be3bfe9.png)

kommune 3427

evnt om man hadde flowcard per type avfall som trigger for å bruke i flow for push varsel om en git type avfall og antall dager.

ser at dager igjen viser, mens neste henting av rest er om 2 dager.

![image](https://user-images.githubusercontent.com/96687238/232751145-1b716b08-b25b-4abd-bb9c-b7aae971c189.png)

slik ser det ut i min renovasjon appen

![Screenshot_20230418-123149223 (1)](https://user-images.githubusercontent.com/96687238/232751324-10593711-2ba1-4fc9-92b9-260f843f5624.png)

**Comment by Coderaxx** [comment]
Hei! Tusen takk for at du gir tilbakemelding! Jeg ser at feil nedtelling til henting er et gjentakende problem. Jeg jobber med en fix, og oppdaterer appen fortløpende! 😄
