### ISSUE TITLE
Sandnes Kommune virker ikke

### ISSUE THREAD

**Issue by Finnsen** [Coderaxx/Norske-tjenester#16]
Hei.

Sandnes Kommune virker ikke. De har sin egen app og sannsynligvis eget API. Appen heter "Renovasjon i Sandnes".

Mvh
Ragnar Anfinsen

**Comment by Coderaxx** [comment]
Hei!
Jeg har tatt en titt på Sandnes, og det ser dessverre ut til at tømmekalenderen deres på nett er ute av drift. Jeg skal holde øynene åpne for når den eventuelt kommer tilbake igjen. Hvis du i mellomtiden har en kalenderfil, eller en pdf med kalenderen, kan jeg klare å hente ut informasjon fra det også.😄
