### ISSUE TITLE
[Renovasjon] Trondheim Renholdsverk (TRV)

### ISSUE THREAD

**Issue by franklovas** [Coderaxx/Norske-tjenester#18]
**Hvilket renovasjonsselskap mangler?**
Trondheim Renholdsverk (TRV)

**Tilleggsinformasjon**
Hvis du har tilleggsinformasjon, skriv det her. Skriv gjerne adressen din her, slik at det blir enklere å legge inn støtte for ditt renovasjonsselskap.
Min adresse er:
Sigrid Johansens veg 8
7025 Trondheim

**Comment by Coderaxx** [comment]
TRV er støttet. Se #23
