### ISSUE TITLE
[Renovasjon] HIM

### ISSUE THREAD

**Issue by alfjonny** [Coderaxx/Norske-tjenester#19]
**Hvilket renovasjonsselskap mangler?**
HIM (Haugalandet)
Mener de skal ha API for å hente ut info

**Tilleggsinformasjon**
Hvis du har tilleggsinformasjon, skriv det her. Skriv gjerne adressen din her, slik at det blir enklere å legge inn støtte for ditt renovasjonsselskap.

**Comment by Coderaxx** [comment]
Jeg prøvde akkurat med din adresse, og det funket fint. Under paring fant den samme adresse hos leverandøren "Glør", men når du blir spurt om det er riktig leverandør, kan du trykke nei, og velge HIM fra listen. 😄

**Comment by alfjonny** [comment]
Gjør det, så er den stuck her:

![image](https://github.com/Coderaxx/Norske-tjenester/assets/17601043/f827d4cb-69e0-4ef2-9bc1-b4165afd21de)

**Comment by Coderaxx** [comment]
Hei igjen. Jeg har pushet en oppdatering som skal fikse problemet. Pass på at du har versjon v2.4.2+
Du kan eventuelt laste ned test-versjonen [her](https://homey.app/no-no/app/com.Coderax.NorwegianServices/Norske-tjenester/test/). Gi meg beskjed dersom det fortsatt ikke funker!🙂

**Comment by alfjonny** [comment]
Da fikk jeg katten tilbake når jeg legger inn addressen 👍😂

søn. 2. jul. 2023, 11:41 skrev Jesper Grimstad ***@***.***>:

**Comment by alfjonny** [comment]
@Coderaxx , er på versjon 2.6.5 pr nå. Får fremdeles feil i addresse og katten.

![image](https://github.com/Coderaxx/Norske-tjenester/assets/17601043/1b2caa07-5142-4dcd-adad-b64287c3699f)

Kan det ha noe med at HIM har 2 addresser i forskjellige kommuner som er like?
En annen ting er at i Norske Tjenester appen finner den addressen Fjellvegen 36, 5563 Førresfjorden - mens HIM sin løsning står det Tysvær (Førresfjorden er i Tysvær kommune). Kan det være et potensielt problem?

![image](https://github.com/Coderaxx/Norske-tjenester/assets/17601043/9efd3675-d83a-4413-9f90-60ea7f6b57cd)

**Comment by Coderaxx** [comment]
Det kan absolutt være problemet ja. Jeg har løst et lignende problem for en annen leverandør. Gi meg en time, så skal jeg sjekke, og få lagt inn fix 😄

**Comment by alfjonny** [comment]
Jeez, det var raskt svar. Utrolig jobb som blir lagt ned i Norske Tjenester appen, godt jobba! PS: Ingen hast for min del dette altså :)

**Comment by Coderaxx** [comment]
Takk for det!😁😅 Ja det går fort litt tid i dette her. Men det er jo gøy også!😆

**Comment by Coderaxx** [comment]
Jeg pushet ut en oppdatering på både app og api nå. Hvis du går inn og oppdaterer appen til v2.6.6, så vil du kunne legge til din adresse 👍🏼

**Comment by Coderaxx** [comment]
Du må gjerne si ifra om det ikke funker, så skal jeg få sett enda mer på det 😅

**Comment by alfjonny** [comment]
Slik ser det ut ved buildt in google addresse:

![image](https://github.com/Coderaxx/Norske-tjenester/assets/17601043/7b0b03c1-c6b8-4ab8-9cd3-46f14abaf4b0)

Feil:
![image](https://github.com/Coderaxx/Norske-tjenester/assets/17601043/9d13abac-c48c-4ca5-9a59-732420d487cf)


Kartverket API søk fungerer ikke i det hele tatt idag.

**Comment by alfjonny** [comment]
@Coderaxx sliter fremdeles med samme addressen :(
Kult med bensinpriser også, helt rått! Hadde vært nice med å fått bensinpris inn i "Insights" for å se bensinpris over lengre tid tilbake for å sammenligne.

**Comment by Coderaxx** [comment]
Hmm.. det var rart. Kunne du opprettet en diagnostikkrapport? Gjelder det fortsatt samme adresse som tidligere? Hvilken versjon av appen kjører du?🙂

**Comment by Coderaxx** [comment]
@alfjonny Det funker hos meg🤔
![](https://img001.prntscr.com/file/img001/KI_jVCOmTm-rvx4KB589eQ.png)

**Comment by Coderaxx** [comment]
@alfjonny Har også lagt til insights logging for drivstoffpriser nå. 👍🏼 Pusher oppdatering snart.😁

**Comment by alfjonny** [comment]
NÅ FUNKA DET! :)

Du er guden!

**Comment by Coderaxx** [comment]
Herlig! Godt å høre😄🤩
