### ISSUE TITLE
[Renovasjon] Vesar (Min Renovasjon)

### ISSUE THREAD

**Issue by tsveri** [Coderaxx/Norske-tjenester#21]
**Hvilket renovasjonsselskap mangler?**
Vesar- Vestfold

**Tilleggsinformasjon**
Hvis du har tilleggsinformasjon, skriv det her. Skriv gjerne adressen din her, slik at det blir enklere å legge inn støtte for ditt renovasjonsselskap.
Fredrik Holts vei 18,3090 Hof

**Comment by Coderaxx** [comment]
Vesar er støttet i appen under "Min Renovasjon"
