### ISSUE TITLE
[Posten] 

### ISSUE THREAD

**Issue by MacMillan88** [Coderaxx/Norske-tjenester#24]
Post enheten har ikke oppdatert seg på 15 dager.
![Screenshot_2023-05-04-07-27-49-15_4bbfc4a7dd885a2bb189f300112a7ed4](https://user-images.githubusercontent.com/54432745/236119340-c268761f-5acb-4c25-9c72-9d9c0ab01e48.jpg)

**Comment by Coderaxx** [comment]
Hei! Hvilken versjon av appen har du?

**Comment by MacMillan88** [comment]
v1.3.3

![Screenshot_2023-06-06-16-34-26-46_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/Coderaxx/NorwegianServicesPublic/assets/54432745/dc55613d-4f7a-4ee3-92a6-8b026cba4bac)

**Comment by Coderaxx** [comment]
Da er du på en utdatert versjon. Prøv å installere appen på nytt her: https://homey.app/no-no/app/com.Coderax.NorwegianServices/Norske-tjenester/
