### ISSUE TITLE
Asker kommune viser feil henting av neste tømming av avfall

### ISSUE THREAD

**Issue by waerpen** [Coderaxx/Norske-tjenester#26]
![Screenshot 2023-05-04 193523](https://user-images.githubusercontent.com/85733797/236284199-62985d1f-1d80-439b-8c6f-0500823fb2ef.png)

Feil på både hvilket avfall som skal hentes, og antall dager.

**Comment by Coderaxx** [comment]
Her er nok nor på tur ja.. Hvilken versjon av appen kjører du?
