### ISSUE TITLE
Renovasjon (Min Renovasjon) viser ikke antall dager til neste henting

### ISSUE THREAD

**Issue by cramsvik** [Coderaxx/Norske-tjenester#27]
Appen viser neste hentedato for en del av de ulike typene avfall (matavfall har ikke oppdatert seg med neste hentedato), men alle de ulike typene avfall viser dager _siden sist_ hentet, ingen viser hvor lenge det er til _neste_ henting.

**Comment by Coderaxx** [comment]
Hei! Dette er en bug som er fikset i siste versjon av appen 1.3.2. Jeg håper å få rullet den ut til test i løpet av kvelden😁 Hvilken versjon av appen kjører du nå?

**Comment by cramsvik** [comment]
Er pr nå på 1.3.1, så da blir det vel årnings etterhvert, tenker jeg. :-D
Er ikke verdens undergang; det er bare kona som klager når flow gir beskjed om å kjøre ned dunk hver kveld. Jeg pausa bare den flowen så lenge. Er inforstått med at det kan våre noe ustabilt i så tidlige versjoner. Synes du har fått til veldig mye bra på kort tid her. 👍

**Comment by cramsvik** [comment]
Hei igjen! Er nå på 1.3.2, men det ser ikke ut til å ha blitt noe bedre (om det ikke oppdateres såpass sjelden at det må gå et døgn, så klart). Ser også at nå er posten i utakt; vi har levering i dag, men det står 1 dag siden og 1 dag til neste.

**Comment by Coderaxx** [comment]
Hei! Beklager sent svar her. Jeg har fikset en del feil i både renovasjon og posten, så hvis du kjører siste versjon av appen, burde alt være fint nå. :) Hvis du fortsatt kjører renovasjon fra da du installerte appen, vil jeg sterkt anbefale å bytte over til renovasjon v2. 👍🏼
