### ISSUE TITLE
[Renovasjon] ROAF (Min Renovasjon)

### ISSUE THREAD

**Issue by olast** [Coderaxx/Norske-tjenester#4]
Roaf-kommunene virker ikke:
http://roaf.no

**Comment by Coderaxx** [comment]
Takk for at du rapporterer! Jeg jobber med å implementere flere renovasjonsselskap, inkludert Roaf! 😄

**Comment by Coderaxx** [comment]
Hei! ROAF kommuner er støttet under "Min Renovasjon". 😄
