### ISSUE TITLE
Røros - noen småfeil

### ISSUE THREAD

**Issue by cbakk1** [Coderaxx/Norske-tjenester#5]
Super app! 😊 Fungerer for det meste for Røros, men viser ikke papp / papir, som har samme hentedato som plast.
Det er dessuten et ikon oppe til venstre som ser ut til å hevde at det er 87 dager igjen til henting av glass / metall, men det stemmer ikke. Riktig dato for glass / metall står til høyre for dette.
![9D6FEECD-9CC5-4AC7-B1E7-AD9A95C9B60B](https://user-images.githubusercontent.com/76168094/232757983-3a02277d-2d54-4ee2-8e4a-2c3933ed8033.png)

**Comment by Coderaxx** [comment]
Takk for at du gir beskjed!😃 Jeg skal se på problemet, og implementere en fix så fort jeg kan!😄
