### ISSUE TITLE
[Renovasjon] Nordre Follo (Follo Ren)

### ISSUE THREAD

**Issue by Emilsolhoi** [Coderaxx/Norske-tjenester#52]
**Hvilket renovasjonsselskap mangler?**
Ønsker å få på plass Follo Ren. 

https://folloren.no/

hilsen,
Emil

**Comment by Coderaxx** [comment]
Follo Ren bruker Min renovasjon, som allerede er støttet! 😄

**Comment by Emilsolhoi** [comment]
@Coderaxx 

hm, pussig. Jeg får feil i min adresse om at den ikke finnes når jeg prøver å legge til ny enhet.

**Comment by Coderaxx** [comment]
Hvilken adresse prøver du med? Jeg skal få tatt en titt med en gang 😄

**Comment by Emilsolhoi** [comment]
@Coderaxx 
Skogsåsen 24D

takk for rask respons :)

**Comment by Coderaxx** [comment]
> @Coderaxx Skogsåsen 24D
> 
> takk for rask respons :)

Hei igjen! Da har jeg identifisert problemet, og implementert en fiks.😁 Ingen oppdatering av appen nødvendig.

**Comment by Emilsolhoi** [comment]
Supert! Da funka det. Tusen takk :)

**Comment by Coderaxx** [comment]
Fikset nettopp en bug der ikke kalenderen kom inn i devicen. Hvis dette skjedde med deg også, bare legg den inn på nytt, så skal det se [slik](https://prnt.sc/7ru5ksapTqaz) ut!😁

**Comment by Emilsolhoi** [comment]
Konge! Funker fjell nå :)
Tusen takk
