### ISSUE TITLE
[Renovasjon] Mangler hageavfall for Stavanger kommune

### ISSUE THREAD

**Issue by proisland** [Coderaxx/Norske-tjenester#57]
I Stavanger kommune har vi beholdere for hageavfall, men dette kommer ikke opp i appen.

**Comment by Coderaxx** [comment]
Takk for info!😄 Jeg har lagt inn støtte for hageavfall, og egentlig alle typer avfall. Har bare ikke sett en eneste adresse jeg har testet med noe annet enn standard avfall.😅 Jeg aktiverer hageavfall i løpet av dagen!😁👨🏼‍💻

**Comment by proisland** [comment]
Om du søker etter en adresse (f.eks Kuneset xx) på Hundvåg i Stavanger kommune så skal du finne det. Hundvåg er første bydel ut hvor alle(?) har fått beholder for hageavfall.

**Comment by Coderaxx** [comment]
Da har jeg aktivert støtte for hageavfall!😁 Ligger ute som test-versjon [her](https://homey.app/no-no/app/com.Coderax.NorwegianServices/Norske-tjenester/test/) nå.
