### ISSUE TITLE
Sunndal kommune virker ikke

### ISSUE THREAD

**Issue by kuliogen** [Coderaxx/Norske-tjenester#7]
Mulig det gjelder alle kommunene som bruker ReMidt

**Comment by Coderaxx** [comment]
Hei! Takk for at du gir beskjed. Det stemmer at ReMidt kommunene ikke vil virke enda. Jeg jobber iherdig med å få på plass flere tilbydere, inkludert ReMidt! 😄

**Comment by Coderaxx** [comment]
ReMidt er nå støttet. Se #39
