### ISSUE TITLE
Postnummer 1679 virker ikke

### ISSUE THREAD

**Issue by loydjoha** [Coderaxx/Norske-tjenester#9]
Får status "Feil" på enhet Renovasjon som er lagt inn med parametere:

Gatenavn: Grågåsveien
Husnummer: 15
Postnummer: 1679
Kommunenr: 3004
Adressekode: 92585

**Comment by Coderaxx** [comment]
Hei! Takk for tilbakemelding. Jeg tar en titt på det. Foreløpig er kun Min renovasjon kommunene støttet, men flere er på vei. Bruker din kommune min renovasjon, eller noen andre digitale hentekalendre? 😄

**Comment by loydjoha** [comment]
Vet ikke hvilken tjenster de bruker, men ja de har elektronisk
hentekalender.

Mvh
Loyd Johansen

tor. 20. apr. 2023, 06:54 skrev Jesper Grimstad ***@***.***>:

**Comment by Coderaxx** [comment]
Fungerer per 25.06.23.
